-- Script de Base de Datos para el Control de Asistencia "Bomba Suiza"
-- Ejecutar en el SQL Editor de Supabase

-- 1. Tabla de Bomberos
CREATE TABLE public.bomberos (
    registro_general VARCHAR(50) PRIMARY KEY,
    nombres VARCHAR(255) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100) NOT NULL,
    rut VARCHAR(20) UNIQUE NOT NULL,
    estado VARCHAR(50) NOT NULL CONSTRAINT chk_bomberos_estado CHECK (estado IN ('Activo', 'Renunciado', 'Separado', 'Expulsado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Tabla de Actos de Servicio
CREATE TABLE public.actos_servicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corr_general INTEGER NULL,
    corr_cia INTEGER NOT NULL,
    fecha DATE NOT NULL,
    clave VARCHAR(100) NOT NULL,
    direccion TEXT NOT NULL,
    tipo VARCHAR(50) NOT NULL CONSTRAINT chk_actos_tipo CHECK (tipo IN ('Efectiva', 'Abono')),
    cantidad_listas INTEGER NOT NULL DEFAULT 1,
    a_cargo_cia VARCHAR(50) REFERENCES public.bomberos(registro_general) ON UPDATE CASCADE,
    tomo_lista VARCHAR(50) REFERENCES public.bomberos(registro_general) ON UPDATE CASCADE,
    total_asistencia INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Tabla de Asistencias (Relación de asistencia de bomberos por acto)
CREATE TABLE public.asistencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_acto BIGINT NOT NULL REFERENCES public.actos_servicio(id) ON DELETE CASCADE ON UPDATE CASCADE,
    reg_bombero VARCHAR(50) NOT NULL REFERENCES public.bomberos(registro_general) ON UPDATE CASCADE,
    cantidad_listas INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT uq_acto_bombero UNIQUE (id_acto, reg_bombero)
);

-- 4. Tabla de Licencias
CREATE TABLE public.licencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_bombero VARCHAR(50) NOT NULL REFERENCES public.bomberos(registro_general) ON DELETE CASCADE ON UPDATE CASCADE,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NOT NULL,
    motivo TEXT NOT NULL,
    aprobado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT chk_licencia_fechas CHECK (fecha_desde <= fecha_hasta)
);

-- 5. Tabla de Movimientos del Personal
CREATE TABLE public.movimientos_personal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_bombero VARCHAR(50) NOT NULL REFERENCES public.bomberos(registro_general) ON DELETE CASCADE ON UPDATE CASCADE,
    fecha_ingreso DATE NOT NULL,
    fecha_salida DATE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT chk_movimiento_fechas CHECK (fecha_salida IS NULL OR fecha_ingreso <= fecha_salida)
);

-- Habilitar RLS (Row Level Security) es una buena práctica en Supabase.
-- Por ahora, si es una base de datos interna de administración, se pueden usar políticas simples.
-- O habilitar acceso general para la key anon en local mientras se desarrolla.
-- Habilitaremos RLS y crearemos políticas básicas para permitir lectura/escritura con la API key anon.
ALTER TABLE public.bomberos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.actos_servicio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asistencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.licencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos_personal ENABLE ROW LEVEL SECURITY;

-- Políticas de bypass simples para propósitos de la app de escritorio
-- (Se asume que la app usa la anon key o service role, creamos política 'allow all' para usuarios autenticados o anon simple)
CREATE POLICY "Permitir todo a bomberos" ON public.bomberos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a actos_servicio" ON public.actos_servicio FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a asistencias" ON public.asistencias FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a licencias" ON public.licencias FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a movimientos_personal" ON public.movimientos_personal FOR ALL USING (true) WITH CHECK (true);
